In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import sqlite3

from pandas import read_sql_query

In [3]:
conn=sqlite3.connect('inventory.db')

In [4]:
tables=pd.read_sql_query(f"select name from sqlite_master where type='table'",conn)
tables

              name
0        purchases
1  purchase_prices
2   vendor_invoice
3  begin_inventory
4    end_inventory

In [7]:
for table in tables['name']:
    print(f'table name:{table}')
    data=pd.read_sql_query(f'select * from {table} limit 5',conn)
    display(data)

table name:purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

table name:purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

table name:vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

table name:begin_inventory

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

table name:end_inventory

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

In [18]:
purchase_agg_df = pd.read_sql_query(""" select

p. PONumber,

count(distinct p.Brand) as total_brands, sum(p.Quantity) as total_item_quantity, sum(p.Dollars) as total_item_dollars, avg(julianday(p.ReceivingDate) - julianday(p.PODate)) as avg_receiving_delay from purchases p group by p. PONumber""",conn)

In [19]:
purchase_agg_df.head()

,PONumber,total_brands,total_item_quantity,total_item_dollars,avg_receiving_delay
0,8106,81,10100,137483.78,12.614130
1,8107,2,24,348.72,12.500000
2,8108,165,8466,60281.13,12.632479
3,8109,23,2246,14298.09,12.626866
4,8110,183,8086,56493.23,12.695271

In [22]:
pd.read_sql_query("""
select
vi.PONumber,

vi.Quantity as invoice_quantity,

vi.Dollars as invoice_dollars,

vi.Freight,
(julianday(vi.InvoiceDate) - julianday(vi.PODate)) AS days_po_to_invoice,

(julianday(vi.PayDate) - julianday(vi.InvoiceDate)) AS days_to_pay

from vendor_invoice vi



""", conn)

,PONumber,invoice_quantity,invoice_dollars,Freight,days_po_to_invoice,days_to_pay
0,8124,6,214.26,3.47,14.0,43.0
1,8137,15,140.55,8.57,16.0,45.0
2,8169,5,106.60,4.61,16.0,38.0
3,8106,10100,137483.78,2935.20,23.0,24.0
4,8170,1935,15527.25,429.20,14.0,36.0
...,...,...,...,...,...,...
5538,13626,90,1563.00,8.60,16.0,35.0
5539,13661,4617,37300.48,186.50,18.0,39.0
5540,13643,9848,202815.78,932.95,11.0,33.0
5541,13602,24747,149007.56,819.54,14.0,36.0
5542,13574,437,3608.11,16.60,18.0,38.0

In [24]:
df=pd.read_sql_query("""
WITH purchase_agg AS (
    SELECT
        p.PONumber,
        COUNT(DISTINCT p.Brand) AS total_brands,
        SUM(p.Quantity) AS total_item_quantity,
        SUM(p.Dollars) AS total_item_dollars,
        AVG(
            julianday(p.ReceivingDate) - julianday(p.PODate)
        ) AS avg_receiving_delay
    FROM purchases p
    GROUP BY p.PONumber
)

SELECT
    vi.PONumber,
    vi.Quantity AS invoice_quantity,
    vi.Dollars AS invoice_dollars,
    vi.Freight,
    (julianday(vi.InvoiceDate) - julianday(vi.PODate)) AS days_po_to_invoice,
    (julianday(vi.PayDate) - julianday(vi.InvoiceDate)) AS days_to_pay,

    pa.total_brands,
    pa.total_item_quantity,
    pa.total_item_dollars,
    pa.avg_receiving_delay

FROM vendor_invoice vi

LEFT JOIN purchase_agg pa
    ON vi.PONumber = pa.PONumber
""", conn)

In [25]:
#cleaning
df.isnull().sum()

PONumber               0
invoice_quantity       0
invoice_dollars        0
Freight                0
days_po_to_invoice     0
days_to_pay            0
total_brands           0
total_item_quantity    0
total_item_dollars     0
avg_receiving_delay    0
dtype: int64

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5543 entries, 0 to 5542
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PONumber             5543 non-null   int64
 1   invoice_quantity     5543 non-null   int64
 2   invoice_dollars      5543 non-null   float64
 3   Freight              5543 non-null   float64
 4   days_po_to_invoice   5543 non-null   float64
 5   days_to_pay          5543 non-null   float64
 6   total_brands         5543 non-null   int64
 7   total_item_quantity  5543 non-null   int64
 8   total_item_dollars   5543 non-null   float64
 9   avg_receiving_delay  5543 non-null   float64
dtypes: float64(6), int64(4)
memory usage: 433.2 KB

In [27]:
df.dtypes

PONumber                 int64
invoice_quantity         int64
invoice_dollars        float64
Freight                float64
days_po_to_invoice     float64
days_to_pay            float64
total_brands             int64
total_item_quantity      int64
total_item_dollars     float64
avg_receiving_delay    float64
dtype: object

In [28]:
df.corr()

,PONumber,invoice_quantity,invoice_dollars,Freight,days_po_to_invoice,days_to_pay,total_brands,total_item_quantity,total_item_dollars,avg_receiving_delay
PONumber,1.000000,0.049230,0.058917,0.043617,-0.002234,0.012558,0.013423,0.049442,0.059221,-0.042362
invoice_quantity,0.049230,1.000000,0.963831,0.946550,0.000526,0.022284,0.566394,0.706117,0.668171,0.000519
invoice_dollars,0.058917,0.963831,1.000000,0.985141,0.001610,0.025661,0.536952,0.667666,0.679537,0.004694
Freight,0.043617,0.946550,0.985141,1.000000,0.003265,0.025513,0.536381,0.656616,0.670768,0.015645
days_po_to_invoice,-0.002234,0.000526,0.001610,0.003265,1.000000,-0.370432,0.009519,0.005543,0.007931,0.515538
days_to_pay,0.012558,0.022284,0.025661,0.025513,-0.370432,1.000000,0.020336,0.016203,0.015610,-0.029403
total_brands,0.013423,0.566394,0.536952,0.536381,0.009519,0.020336,1.000000,0.783825,0.753092,0.000496
total_item_quantity,0.049442,0.706117,0.667666,0.656616,0.005543,0.016203,0.783825,1.000000,0.963831,-0.014016
total_item_dollars,0.059221,0.668171,0.679537,0.670768,0.007931,0.015610,0.753092,0.963831,1.000000,-0.014251
avg_receiving_delay,-0.042362,0.000519,0.004694,0.015645,0.515538,-0.029403,0.000496,-0.014016,-0.014251,1.000000

In [ ]:
#we have created the data table as we wanted:
#dates they took to pay
#invoice dollars
#the amount they paid
#item_quantity
#what and all brands etc

In [ ]:
#we are going to create a column for labelling data on the criteria
#if there is a big difference in invoice and payed
#if they have taken more days to pay

In [29]:
def create_invoice_risk_labeling(row):
    if abs(row['total_item_dollars']-row['invoice_dollars'])>5:
        return 1
    if row['avg_receiving_delay']>10:
        return 1

    else:
        return 0
df['flagging_invoice']=df.apply(create_invoice_risk_labeling,axis=1)
df['flagging_invoice'].value_counts()

flagging_invoice
0    3693
1    1850
Name: count, dtype: int64

In [82]:
df.head()

,PONumber,invoice_quantity,invoice_dollars,Freight,days_po_to_invoice,days_to_pay,total_brands,total_item_quantity,total_item_dollars,avg_receiving_delay,flagging_invoice
0,8124,6,214.26,3.47,14.0,43.0,1,6,214.26,12.000000,1
1,8137,15,140.55,8.57,16.0,45.0,2,15,140.55,10.333333,1
2,8169,5,106.60,4.61,16.0,38.0,1,5,106.60,9.000000,0
3,8106,10100,137483.78,2935.20,23.0,24.0,81,10100,137483.78,12.614130,1
4,8170,1935,15527.25,429.20,14.0,36.0,29,1935,15527.25,8.752809,0

In [ ]:
#feature selection on the basis of corr and
# significancant difference in features of those who got flagged and not flagged

In [31]:
flagged=df[df['flagging_invoice']==1]
normal=df[df['flagging_invoice']==0]

In [33]:
#t_test and hypthesis testing
df.columns

Index(['PONumber', 'invoice_quantity', 'invoice_dollars', 'Freight',
       'days_po_to_invoice', 'days_to_pay', 'total_brands',
       'total_item_quantity', 'total_item_dollars', 'avg_receiving_delay',
       'flagging_invoice'],
      dtype='str')

In [34]:
metrics=['invoice_quantity', 'invoice_dollars', 'Freight',
       'days_po_to_invoice', 'days_to_pay', 'total_brands',
       'total_item_quantity', 'total_item_dollars', 'avg_receiving_delay',
       ]
significant_feature=[]
non_significant_feature=[]
result=[]

In [35]:
from scipy.stats import ttest_ind
for metric in metrics:
    flagged_mean=flagged[metric].mean()
    normal_mean=normal[metric].mean()

    t_value,p_value=ttest_ind(
        flagged[metric].dropna(),

        normal[metric].dropna(),
        equal_var=False

    )

    if p_value<0.05:
        significant_feature.append(metric)
        result.append(
            {'metric':metric,
             'flagged_mean':flagged_mean.round(2),
             'normal_mean':normal_mean.round(2),
             'p_value':p_value.round(3)}
        )
    else:
        non_significant_feature.append(metric)
        result.append(
            {'metric':metric,
             'flagged_mean':flagged_mean.round(2),
             'normal_mean':normal_mean.round(2),
             'p_value':p_value.round(3)}
        )

In [36]:
significant_feature,non_significant_feature

(['invoice_quantity',
  'invoice_dollars',
  'Freight',
  'days_po_to_invoice',
  'total_item_quantity',
  'total_item_dollars',
  'avg_receiving_delay'],
 ['days_to_pay', 'total_brands'])

In [37]:
#non_significant features will be removed
result

[{'metric': 'invoice_quantity',
  'flagged_mean': np.float64(6728.28),
  'normal_mean': np.float64(5723.55),
  'p_value': np.float64(0.021)},
 {'metric': 'invoice_dollars',
  'flagged_mean': np.float64(65600.61),
  'normal_mean': np.float64(54302.64),
  'p_value': np.float64(0.008)},
 {'metric': 'Freight',
  'flagged_mean': np.float64(334.02),
  'normal_mean': np.float64(276.89),
  'p_value': np.float64(0.008)},
 {'metric': 'days_po_to_invoice',
  'flagged_mean': np.float64(17.23),
  'normal_mean': np.float64(16.02),
  'p_value': np.float64(0.0)},
 {'metric': 'days_to_pay',
  'flagged_mean': np.float64(35.42),
  'normal_mean': np.float64(35.49),
  'p_value': np.float64(0.692)},
 {'metric': 'total_brands',
  'flagged_mean': np.float64(42.29),
  'normal_mean': np.float64(40.82),
  'p_value': np.float64(0.508)},
 {'metric': 'total_item_quantity',
  'flagged_mean': np.float64(6728.28),
  'normal_mean': np.float64(5723.55),
  'p_value': np.float64(0.021)},
 {'metric': 'total_item_dollars',
  'flagged_mean': np.float64(65600.61),
  'normal_mean': np.float64(54302.64),
  'p_value': np.float64(0.008)},
 {'metric': 'avg_receiving_delay',
  'flagged_mean': np.float64(8.47),
  'normal_mean': np.float64(7.27),
  'p_value': np.float64(0.0)}]

In [57]:
x=df[['invoice_quantity',
  'invoice_dollars',
  'Freight',
  'days_po_to_invoice',
  'total_item_quantity',
  'total_item_dollars',
      'total_brands'
  ]]

y=df['flagging_invoice']

In [1]:
x.describe()

NameError: name 'x' is not defined

In [59]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [60]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.20)

In [61]:
std=StandardScaler()
x_train_scaled=std.fit_transform(x_train)
x_test_scaled=std.transform(x_test)

In [62]:
model1=LogisticRegression()
model1.fit(x_train_scaled,y_train)

model2=DecisionTreeClassifier()
model2.fit(x_train_scaled,y_train)

model3=RandomForestClassifier()
model3.fit(x_train_scaled,y_train)

RandomForestClassifier()

In [64]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

def evaluate_model(model,x_test,y_test,model_name):
    y_predict=model.predict(x_test)

    accuracy=accuracy_score(y_test,y_predict)
    print(f"=== {model_name} Performance ===")
    print(f"Accuracy: {accuracy:.4f}\n")
    print("Classification Report:")
    print(classification_report(y_test, y_predict))
    print("-" * 40)

In [65]:
evaluate_model(model1, x_test_scaled, y_test, 'Logistic Regression')
evaluate_model(model2, x_test_scaled, y_test, 'Decision Tree Classifier')
evaluate_model(model3, x_test_scaled, y_test, 'Random Forest Classifier')

=== Logistic Regression Performance ===
Accuracy: 0.6583

Classification Report:
              precision    recall  f1-score   support

           0       0.66      0.98      0.79       725
           1       0.56      0.06      0.11       384

    accuracy                           0.66      1109
   macro avg       0.61      0.52      0.45      1109
weighted avg       0.63      0.66      0.55      1109

----------------------------------------
=== Decision Tree Classifier Performance ===
Accuracy: 0.8124

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.87      0.86       725
           1       0.74      0.71      0.72       384

    accuracy                           0.81      1109
   macro avg       0.79      0.79      0.79      1109
weighted avg       0.81      0.81      0.81      1109

----------------------------------------
=== Random Forest Classifier Performance ===
Accuracy: 0.8765

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.98      0.91       725
           1       0.95      0.68      0.79       384

    accuracy                           0.88      1109
   macro avg       0.90      0.83      0.85      1109
weighted avg       0.89      0.88      0.87      1109

----------------------------------------

In [66]:
print("Train:", model3.score(x_train_scaled, y_train))
print("Test :", model3.score(x_test_scaled, y_test))

Train: 0.9997744700045106
Test : 0.8764652840396754

In [67]:
model3.feature_importances_

array([0.15162797, 0.15334365, 0.13899415, 0.07744912, 0.17679666,
       0.21592154, 0.08586692])

In [68]:
feature_importance=pd.DataFrame({
    'feature_name':x_train.columns,
    'importance':model3.feature_importances_
}).sort_values(by='importance',ascending=False)

feature_importance

          feature_name  importance
5   total_item_dollars    0.215922
4  total_item_quantity    0.176797
1      invoice_dollars    0.153344
0     invoice_quantity    0.151628
2              Freight    0.138994
6         total_brands    0.085867
3   days_po_to_invoice    0.077449

In [70]:
x = df[['invoice_quantity',
        'invoice_dollars',
        'Freight',

        'total_item_quantity',
        'total_item_dollars',

        ]]

y = df[ ]

In [71]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, test_size=0.20)

In [72]:
std = StandardScaler()
x_train_scaled = std.fit_transform(x_train)
x_test_scaled = std.transform(x_test)

In [73]:
model1 = LogisticRegression()
model1.fit(x_train_scaled, y_train)

model2 = DecisionTreeClassifier()
model2.fit(x_train_scaled, y_train)

model3 = RandomForestClassifier()
model3.fit(x_train_scaled, y_train)

RandomForestClassifier()

In [74]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


def evaluate_model(model, x_test, y_test, model_name):
    y_predict = model.predict(x_test)

    accuracy = accuracy_score(y_test, y_predict)
    print(f"=== {model_name} Performance ===")
    print(f"Accuracy: {accuracy:.4f}\n")
    print("Classification Report:")
    print(classification_report(y_test, y_predict))
    print("-" * 40)

In [75]:
evaluate_model(model1, x_test_scaled, y_test, 'Logistic Regression')
evaluate_model(model2, x_test_scaled, y_test, 'Decision Tree Classifier')
evaluate_model(model3, x_test_scaled, y_test, 'Random Forest Classifier')

=== Logistic Regression Performance ===
Accuracy: 0.6546

Classification Report:
              precision    recall  f1-score   support

           0       0.65      1.00      0.79       725
           1       0.60      0.01      0.02       384

    accuracy                           0.65      1109
   macro avg       0.63      0.50      0.40      1109
weighted avg       0.64      0.65      0.52      1109

----------------------------------------
=== Decision Tree Classifier Performance ===
Accuracy: 0.8350

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.87      0.87       725
           1       0.76      0.77      0.76       384

    accuracy                           0.83      1109
   macro avg       0.82      0.82      0.82      1109
weighted avg       0.84      0.83      0.84      1109

----------------------------------------
=== Random Forest Classifier Performance ===
Accuracy: 0.8864

Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.98      0.92       725
           1       0.94      0.72      0.81       384

    accuracy                           0.89      1109
   macro avg       0.90      0.85      0.87      1109
weighted avg       0.89      0.89      0.88      1109

----------------------------------------

In [77]:
print("Train:", model3.score(x_train_scaled, y_train))
print("Test :", model3.score(x_test_scaled, y_test))

Train: 0.9986468200270636
Test : 0.8863841298467088

In [86]:
#hyper_parameter_tuning , next
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer,f1_score

rf=RandomForestClassifier(
    random_state=42,
    n_jobs=-1
)

param_grid={

"n_estimators": [100,200, 300],

"max_depth": [None, 4, 5, 6],

"min_samples_split": [2, 3, 5],

"min_samples_leaf": [1, 2, 5],

"criterion": ['gini', 'entropy']

}

In [87]:
scorer=make_scorer(f1_score)

gridcv=GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    scoring=scorer,
    cv=5,
    verbose=2,
    n_jobs=-1
)

gridcv.fit(x_train_scaled,y_train)
evaluate_model(gridcv,x_test_scaled,y_test,'GRID SEARCH CV')

Fitting 5 folds for each of 216 candidates, totalling 1080 fits
=== GRID SEARCH CV Performance ===
Accuracy: 0.8900

Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.98      0.92       725
           1       0.96      0.71      0.82       384

    accuracy                           0.89      1109
   macro avg       0.91      0.85      0.87      1109
weighted avg       0.90      0.89      0.89      1109

----------------------------------------